### ISSUE TITLE
react_rev

### ISSUE THREAD

**Issue by maringos** [Waschina/cobrar#4]
Dear Team,

many thanks for your great work. In `sybil`, the `modelorg` contains also a `react_rev` vector. I cannot find it when I use `cobrar`. Is it implemented?

Best,
Yorgos

**Comment by Waschina** [comment]
We have omitted the `react_rev` slot because it is redundant information, since the reversibility can be inferred from the lower and upper bounds of a reaction: If a reaction has lb < 0 and lb > 0, the reaction is reversible. In sybil a reaction that was defined to operate only in the backwards direction "A <- B" were incorrectly flagged as reversible. This inconsistency was fixed in cobrar.
