### ISSUE TITLE
cobrar compilation is incompatible with libsbml 5.20.4

### ISSUE THREAD

**Issue by Porthmeus** [Waschina/cobrar#5]
I had problems installing cobar with libsbml version 5.20.4 - it seems that the version is messing with the namespace of the libsbml file which leads to errors during compilation. (see screenshot)

![image](https://github.com/user-attachments/assets/35dfdac5-fffb-4b12-acc9-f596b218cc1e)

Downgrading to libsbml 5.18.4 solved the problem.

While figuring that out, I also noticed, that a relatively recent version of g++ is required, which needs to be compatible with CXXABI_1.3.15 in the libstdc++6.so. This was not the case with my systems default (Ubuntu 22.04) - just as a side note.

Hope that helps maintaining the code,
Cheers, Jan

**Comment by Waschina** [comment]
Thanks for posting the issue.

### g++ required version
The dependency "libgcc-ng >=12" comes from the latest bioconda build for libsbml=5.20.4, not from cobrar. So there's nothing we could do as cobrar developers. When using conda, make sure to add conda-forge to your channels (`conda config --append channels new_channel`). conda-forge has the required libgcc-ng version builds.

### libsbml namespace
Explicitly adding "libsbml" to the namespace seems to be required when using the libsbml 5.20.4 build from bioconda. What I don't know is if this is required because of the new libsbml version or by the GCC 12 (or higher) compiler version. Libsbml version 5.20.2 with GCC 11 worked without adding "libsbml" to the namespace... I have added a quick fix to the cobra code so cobrar also compiles with the the latest libsbml 5.20.4 build from bioconda. I'll leave the issue open until i fully understand this source of the namespace error and have a stable fix.

Ideally, cobrar remains compatible with any libsbml version >=5.18.0.

**Comment by Waschina** [comment]
The problem should be fixed now.

Thanks again for posting the issue!
